site_name: MyMKs
nav:
  - Home: index.md
  - About: about.md
theme:
    name: material

markdown_extensions:
    # コードハイライトの設定
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: false
    # アラート修飾の設定
    - admonition
    # スーパーフェンス機能の設定
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
 